### ISSUE TITLE
stuck at "REMOVE_FLUID"

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [Kotori316/QuarryPlus#126]
MC 1.17.1
fabric-api-0.37.1+1.17.jar
AdditionalEnchantedMiner-1.17-fabric-17.0.342.jar
issue
place a quarry just over ocean ( no marker)
attach power
frames are build 
but whew try to remove first solid water
stuck at "REMOVE_FLUID" , checked with status checker

as well, quarry do not pass fluids to tech.rborn.tank ( may tech.reborn issue ) , less important

I wanted to strip a ocean.monument, no luck
just as info for me: how big is the item buffer of the device ( its huge, i know)

best regards
daniel

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
sorry, my stupid
works well with AdditionalEnchantedMiner-1.17-fabric-17.0.344.jar
would appreciate buffer info
daniel

**Comment by Kotori316** [comment]
The pump problem was, as you noticed, fixed in a5e4013ce216b8f0bcdc46457b9cda7430eee833.

Now quarry can't push to tanks from TR. It is because TR tanks use their own system to treat fluids, which has less accessibility from other mods. This problem will be solved in next release of TR, as [this commit](https://github.com/TechReborn/TechReborn/commit/fd9d776b4304527819c5a8e43c6ac66e9e5a0578) introduces common API to transfer fluids. QuarryPlus has already worked for this new common API, and I checked quarry can push fluids to TR tanks in the development build of TR.

The item buffer of quarry plus is the max value of LONG, 2^63, for each item respecting NBT. The storage is saved with tile data, so the items will not disappear if you quit the game. (The items will go to void if you remove QuarryPlus.)
