### ISSUE TITLE
Crashing when opening the workbench

### ISSUE THREAD

**Issue by jimozzo** [Kotori316/QuarryPlus#139]
> 
> ## Describe the bug
> 
> 
Whenever i open the Workbench Plus the modpack crash!
> ## To Reproduce
> 
> Steps to reproduce the behavior:
> 
>  Place a Workbench Plus and interact with it
> 
> ## Crash report
[crash-2021-10-13_16.39.43-server.txt](https://github.com/Kotori316/QuarryPlus/files/7339403/crash-2021-10-13_16.39.43-server.txt)

**Comment by Erabior** [comment]
I'm also getting this error

**Comment by Kotori316** [comment]
Fixed in v17.5-SNAPSHOT
Thank you for reporting.

**Comment by Erabior** [comment]
it's causing an instant crash on the latest version. exit code 0

**Comment by Kotori316** [comment]
@Erabior 
The message launcher gives is always USELESS. Please give me more detail.
* Forge version. I heard 37.0.8x doesn't work due to some bugs of loading and gives useless message. I recommend 37.0.90
* log file(latest.log and debug.log if exists)
* Did you install [this mod](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force)? I added it as dependency since 17.5

**Comment by Erabior** [comment]
> @Erabior The message launcher gives is always USELESS. Please give me more detail.
> 
> * Forge version. I heard 37.0.8x doesn't work due to some bugs of loading and gives useless message. I recommend 37.0.90
> * log file(latest.log and debug.log if exists)
> * Did you install [this mod](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force)? I added it as dependency since 17.5

sorry, did not see the other mod as a requirement. my bad.
