### ISSUE TITLE
Crash when placing expanded storage chest above quarry

### ISSUE THREAD

**Issue by Erabior** [Kotori316/QuarryPlus#140]
## Describe the bug

game crashed after placing a netherite chest on top of a quarry
## To Reproduce

1. place down a quarryplus
2. place a chest from expanded storage on top

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.17.1]
* Single Player or Multi Player?: [single]
* Forge version: [37.0.95]
* QuarryPlus version: [17.5]
* Other mods: [expandedstorage-7.2.5+1.17.1]

## Crash report or logs

https://pastebin.com/uqEMZPuN

**Comment by Kotori316** [comment]
As I tested in my world, the crash didn't happen. Can this problem be reproduced in minimum environment with Forge, this mod, and expandedstorage?

And, this crash is strange because this error message implies programing error of the author, but I don't think the author did such a mistake. This problem happens only in an environment with a lot of mods.
