### ISSUE TITLE
[1.18] - Ability to "Replace/Fill while operating" 

### ISSUE THREAD

**Issue by idnthvn** [Kotori316/QuarryPlus#165]
Minecraft 1.18
Modpack: All the mods 7

Really what it says above. Unless i have overlooked it.
Possibility to have the void fill with Dirt or Cobblestone as to not leave a giant hole in the ground? 
Could be an "upgrade" or just an option. Could have it even with just a straight replacement or that the player must have the items in an adjacent chest with those items. I swear that the old Quarry in BC or the old Quarry Plus use to change everything to dirt while i mined, but i could be mistaken. Trying to remember back in the 1.7.10 days. But just an idea! Thank you :)

**Comment by Kotori316** [comment]
I added Filler and Filler Module in v18.6. (Now forge only)
Put Filler module into the module slot in a machine, then it will fill with Stone or something like that after the creating "a giant hole". It requires no blocks but energy. It seems odd because it works as infinite material supplier, but I think this setting is better than pulling items from adjacent inventory. In theoretical, you must prepare additional blocks to fill the hole, as the number of required block is over the number you got from the quarry. Then you may encounter a situation where you have waited for a long time but the work isn't finished due to shortage of blocks to fill. So, the machine requires energy instead of blocks.

I'm afraid but I've never heard that quarry replace blocks to Dirt in 1.7.10. (A quarry from Extra Utilities2?) And I hardcoded to use Stone(not Dirt) to fill a hole.
