### ISSUE TITLE
Quarry Plus won't transfer blocks SERVER SIDE

### ISSUE THREAD

**Issue by djkriss0804** [Kotori316/QuarryPlus#188]
Hello im have an issue about using Quarry Plus on server because after mining blocks im don't receive any drop in the chest on the basic config but when i'm drop under the laser any item then quarry pick up those and transfer items to the hest but non items breaking by self but on single player all working correct just i'm have this problem when im trying use this on server. 

"sorry about my English (still learning)"

 "version": "12.5.6",
 "mcversion": "1.12.2"

**Comment by Kotori316** [comment]
In my development environment, the quarry worked fine in server world, transferring dropped items to adjacent inventory.

This kind of problems is caused by other mods. Remove or add other mods one by one to find which mod prevents the blocks from being dropped. With the minimum requirements(Forge, QuarryPlus, JEI, and Waila), the quarry should work as expected.

**Comment by FabianMain** [comment]
I had the same issue. I solved it by removing the AuthMe authorization plugin from the assembly.
