### ISSUE TITLE
Marker Plus Alternative

### ISSUE THREAD

**Issue by allpurposebucket** [Kotori316/QuarryPlus#239]
With the removal of the MarkerPlus in 1.19, what is the intended way to change boundaries on the QuarryPlus?

I'm playing through ATM8 and the asset is in JEI, although there is no recipe.

**Comment by allpurposebucket** [comment]
I'm now seeing this issue #169 , is this what caused the removal?

**Comment by Kotori316** [comment]
It is the rendering issue.
The marker shows blue line when it receives RS signal. It is a guide to place other markers. (like [this](https://github.com/Kotori316/QuarryPlus/wiki/MarkerPlus))
The issue is that the line disappears when you are far from the first marker. It doesn't appear unless you change the RS state.
It seems the marker is unloaded. Then the guide line disappears.

The alternative way to select area is to use **other markers**, [Flexible Marker](https://github.com/Kotori316/FlexibleMarker/wiki/FlexMarker) or [Chunk Marker](https://github.com/Kotori316/FlexibleMarker/wiki/ChunkMarker), which are available in QuarryPlus for 1.19.
I'll update QuarryPlus wiki to introduce these markers.

**Comment by Kotori316** [comment]
There are no problems in the work of Marker Plus.
The recipe was removed but the function is remained and supported in future version because the marker is useful in debugs of other machines.
