### ISSUE TITLE
Chunk destroyer UI redesign

### ISSUE THREAD

**Issue by Mihoshika** [Kotori316/QuarryPlus#240]
Chunk destroyer currently starts whenever it's got power, regardless of what you set for its settings. This can make you need to break it, and replace it, and race to set up your settings.

I'd like for it to only start after you do a setup of sorts, where right click it, and enter options, then press 'start'. 

Options that would be nice: 
- Dimensions. Pretty self explanatory. Maybe include something showing the coordinates or block size of the mining area.
- Mining direction. Currently, it goes across sideways, so it's constantly loading new chunks, especially at full speed. It's a lot more economic, server resource-wise, if it were to stay within a single chunk until that was finished. Would also be a bit more accurately named if it targeted a single chunk by default.
- No frame. I am assuming the button in the current UI is supposed to stop/prevent it from generating a frame, which it doesn't seem to. The frame doesn't really do much, and causing a decent bit of lag when it's generating. Having this as an option before you start would let you choose whether you want the frame or not.
- Void filters. Choose blocks you don't want to collect. Good option, especially in servers/modpacks that allow chunk destroyer to collect things such as cobble/netherrack, etc.

**Comment by Kotori316** [comment]
I don't need start button because connecting energy supplier is a sign to start the machine. Place machine, connect power source, and the machine starts. It's simple. This is not a way to start electrical instruments in your home, but from era of BuildCraft, it is common in Minecraft. I don't need, but it's just an opinion. Others need the button. It should be a config option(such as autoStartMachines).
You suggested a step by step configuration, but do you need to configure the options every time you run the Quarry? I think you never turn on the frame option. The configuration GUI might be useful for new users, but I want them to use default setting, not to make them confused with many meaningless options.
I'm sorry for the lag when quarry starts placing frames. I'm aware of this problem, but I don't have any ideas for it.
Mining direction is a good point to improve performance. I don't know how many chunks are "destroyed" by the machine in just one time(for me, only 9 or 25), so I should consider the threshold for changing the direction behavior. If the area is small, keep current behavior. If large, chunk by chunk mining will be good. Of course, this is configurable in config file(default on).
You can remove the machine block with modules are inside. The tooltip shows the modules in the machine item. You don't have to configure it every time. I don't think the target block changes very often.

Conclusion
Start button -> configurable
Setup step -> I don't like
No frame -> I think configurable is good
Void module -> Don't take the module.

Thank you for your request. 😄

**Comment by Mihoshika** [comment]
Not sure what mod in the modpack is doing it, but the chunk destroyer gets energy passively, so it will start (especially at lower power requirements) on its own. 

Not exactly aiming for a step by step configuration. Just options people could tick if they want to change something. If you look at something like the RFTools builder, it's highly configurable, even ignoring the card system. Actually, it's quite similar in function to the chunk destroyer, if a bit lacking in power. 

The glowing lines that show up when you're setting the size of the chunk destroyer are pretty much all you need when setting it up, since they show the direction(s) your expanding. The frame is somewhat pointless, but you can keep it as a configurable option, or maybe make it client-side. (Only showing to owner, or maybe person who pressed the option to show it.) The frame seems to be a carryover from other QuarryPlus machines, for which it's actually useful to have a 3d representation of the area you're mining. Not the case for chunk destroyer, though.

Wasn't actually aware there was a void module. I'll look into it later.

The whole point of it being at least somewhat configurable in-game, and not in a config file, is both ease of use, and allowing players on servers the ability to change how things work. If you don't want to go that way, though, that's entirely up to you. These are just suggestions.

**Comment by Kotori316** [comment]
I'm working to add check box like this.
![2023-03-03_14 57 25](https://user-images.githubusercontent.com/28705167/222642980-f16aaed3-3143-4261-bb69-2e350a3abeae.png)

**Comment by Kotori316** [comment]
Sorry for the delay, but I uploaded a new version, [v19.10.9](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/4438121).

You can change these 3 configs in GUI. The default is loaded from client config even in server world. If you find preferred one, write it to your client config(`quarryplus-client.toml`).
If "Ready to Start" is off, the machine doesn't start when energy is supplied. After clicking "Start" or check "Ready to Start", the machine starts to work.
