### ISSUE TITLE
[1.20.1] Crash after placing Chunk Destroyer, FTBChunks related

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [Kotori316/QuarryPlus#263]
## Describe the bug

Crash after placing a chunk destroyer in creative, FTBChunks integration related
also yes, I am on ATM9, but probably the only 2 important mods here are QuarryPlus and FTBChunks as there's no other mod in the backtrace

## To Reproduce

1. Have FTBChunks
2. Place the Chunk Destroyer
3. crash

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.20.1
* Single Player or Multi Player?: Singleplayer
* Forge version: 47.0.35
* QuarryPlus version: 1.20.1-1201.0.10-SNAPSHOT
* Other mods: FTB Chunks 2001.1.2
## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.
https://gist.github.com/rozbrajaczpoziomow/81046b766f8798e297b6eb9a41acc9c6

**Comment by Kotori316** [comment]
I think I fixed this yesterday, but a similar problem happens.
Your report says `java.lang.NoClassDefFoundError: dev/ftb/mods/ftbchunks/api/FTBChunksAPI` with FTB Chunk(`ftb-chunks-forge-2001.1.2.jar`). The reporter yesterday says `java.lang.NoClassDefFoundError: dev/ftb/mods/ftbchunks/data/FTBChunksAPI` with `ftb-chunks-forge-2001.1.3.jar`. Did FTB Chunk change its API in this version?

I think the problem is FTB Chunks changed API in minor version, and I can't do anything for this problem because I should always support the latest version of libraries. I'm very sorry.

Try one of followings. Never do BOTH.
* Downgrade my mod to 1201.0.9-SNAPSHOT
* Upgrade FTB Chunks to 2001.1.3

**Comment by Kotori316** [comment]
If you have any problem on this issue, please tell me.

**Comment by Kotori316** [comment]
This change caused this issue. https://github.com/FTBTeam/FTB-Chunks/commit/e376d77e2b4f470dd38a6136eeb008b01cd3d736
This commit may be included in the latest version of FTB Chunk.

**Comment by rozbrajaczpoziomow** [comment]
Why would any sane dev ever change their API within a minor version change...
I know SemVer isn't the best but at least it's better than this BS

Also very fast response time 11/10

**Comment by jkdude2001** [comment]
Hello,
I am having the same issue on my server, as soon as you place a chunk destroyer it crashes.
https://pastebin.com/kCA0Dr7k

**Comment by rozbrajaczpoziomow** [comment]
The dev already said how to fix it, see above
