### ISSUE TITLE
Problem with FTB chunks

### ISSUE THREAD

**Issue by Astarthean** [Kotori316/QuarryPlus#270]
## Describe the bug

_What happened to you?_

I used a solid fuel quarry in the Allthemodium mining dimension and when I claim and load the chunks, the quarry stops collecting items, even though the quarry still works

I've modified the values within the modpack. I realized that the quarry's functionality with FTB chunks was disabled. I activated it, and it still doesn't work.

I also tried setting my FTB teams' permissions to public, and it still doesn't mine the blocks

I also tried leaving the dimension without claiming the chunks to see if it would work on its own, but it still didn't work

## To Reproduce

1. Place the quarry in the mining dimensión
2. Claim and load the chunks
3. The quarry continues to operate and descend in Y-level, but it doesn't mine any block

## Versions

* Minecraft version: 1.19.2
* Single Player or Multi Player?: Single Player
* Forge version: 43.2.14
* QuarryPlus version: 1192.2.1
* Other mods: ATM8 https://www.modpackindex.com/modpack/50949/all-the-mods-8-atm8

## Crash report or logs

There's no Crash or logs

**Comment by Kotori316** [comment]
Stop claiming the chunks. Quarry never works in claimed chunks to prevent loss of items. Quarry doesn't check anything but whether the chunk is claimed, so changing FTB team configuration is meaningless.
If you already unclaimed the chunks, try to set `true` for `allowWorkInClaimedChunkByFBTChunks` in config. In this case, quarry won't check the claimed area, so don't report any item losses because it's intended.

I don't follow recent change in FTB Chunk, so my detection logic may be wrong. If you have confidence or you're trying test, changing `allowWorkInClaimedChunkByFBTChunks` in config will help you.
