### ISSUE TITLE
Crash from the quarry running

### ISSUE THREAD

**Issue by grydian** [Kotori316/QuarryPlus#68]
https://pastebin.com/8j14s2a5

It says it's trying to combine different kinds of items.  Not sure what's happening.  Using minecraft 1.12.2 and using 12.2.6 of the mod.  Thanks for your help.

**Comment by Kotori316** [comment]
I can't reproduce your crash but I added some code to prevent the crash.
Please try [v12.2.7](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2803010) and tell me whether the crash is fixed.

Crash report said you tried to combine `Null` item but I don't know where it comes from. Vanilla blocks never produce null item drops and other mods don't do it. It might come from moon stone from Extra Utilities because Waila tooltip for the block shows nothing, it's not normal behavior.

**Comment by grydian** [comment]
Fixed the error.  My save is working perfectly now.  Thank you so much!
