### ISSUE TITLE
[1.14.4] Are the recipes enabled? (multiplayer)

### ISSUE THREAD

**Issue by Milii20** [Kotori316/QuarryPlus#70]
Greetings, i have been playing with your mod in 1.14.4 for testing purposes, and by using it along with the mod Silent Mechanisms, cyclic (for FE energy transfer) and Solar Generation (for energy generation), and everything works like a charm (including all the machines with NoEnergy disabled (thus consuming energy and working correctly), but i am missing the recipes for everything other than the solid fueled quarry, and the Workbench Plus, and this last one, once placed looks like this:
![2019-10-17_19 15 53](https://user-images.githubusercontent.com/10578092/67051847-a7e4b600-f112-11e9-87cc-34a5de3ee8ee.png)

**Comment by Kotori316** [comment]
I made an environment of 1.14.4, with Forge, my mods, Silent Mechanisms, cyclic, Solar Generation and libraries.
But your problem didn't happen.

Textures and recipes are changed by resource pack and data pack.
The block seems it has transparent texture.

Are you in multi player server? And, do you use any resource or data packs?
I'll update my developing environment and check any errors.

**Comment by Milii20** [comment]
Greetings! thank you for the fast response, I can confirm many things:

1) The visual bug was purely related to having forge 28.1.44, i updated to 28.1.61 and it's all fixed

2) i was able to reproduce the recipe problem with the following list of mods: 
![image](https://user-images.githubusercontent.com/10578092/67227821-6c960000-f40e-11e9-8bcf-8f0598a76abe.png)

3) The recipe issue is only on multiplayer servers, the recipes are there in singleplayer

4) not using any kind of resourcepack or datapacks, i even tried in an empty world to be sure

5) i dont know if this will mean anything, but since multimc doesnt support 1.14.4 yet, i am using twitch's launcher, and  forge 28.1.61

**Comment by Kotori316** [comment]
It seems that client do not load data packs on connecting server. Once you load single player world, the recipe will shown. The launcher doesn't matter because the problem happens in development environment.
**Before loading recipe in client**
![2019-10-24_01 57 36](https://user-images.githubusercontent.com/28705167/67416548-fa860c80-f601-11e9-99d9-cbfa60267da2.png)
**After loading recipe in client**
![2019-10-24_01 59 10](https://user-images.githubusercontent.com/28705167/67416641-23a69d00-f602-11e9-888d-ac448bbe96fc.png)
But this is not a good solution because client can't get modified recipe in server world. Even if you use data pack to change workbench recipe, client screen and JEI shows wrong recipes.

**Comment by Kotori316** [comment]
Uploaded new version, [v14.1.1](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2815191).

**Comment by Milii20** [comment]
All good and working now, thank you very much!
