### ISSUE TITLE
PumpPlus get stuck when reaching large amount of liquids. QuarryPlus 12.3.5 on Minecraft 1.12.2

### ISSUE THREAD

**Issue by Alexlion2308** [Kotori316/QuarryPlus#85]
**Describe the bug**
I have a quarryplus 256x256 enchanted Efficiency5 Fortune3 and Unbreakable3 with a Pumpplus.
There is some liquide on middle layer (30/50) so the pump do its work. but when it comes to low layer with lava, the pump work but after few times it stucks and stops the quarry plus.
I don't know if thats my version, but i remember in 1.7.10 i didn't get this problem.
So i lauched the quarryplus without pumpplus but the large amount of liquids staying makes a lot of lags :/

It tryed to modify configuration file and set noEnergy to true solve the problem it seems.

With the noEnergy is set to false, the quarryplus cumsuption is normal (ossilating between 95-100% of max energy capacity) when it break bloks with my power supplie, but when it switchs on pump mode and get stuck, it ossilating between 0-10% of its capacity. 

So maybe a highly cumsuption problem. 

**To Reproduce**
1. Launch quarryplus and wait lower layers
or
2. Launch quarryplus and wait it finnish ans relauch with pumpplus attached

**Version**
* Minecraft: [1.12.2] 
* Forge: [14.23.5.2846] 
* This mod (QuarryPlus): [12.3.5] 
* Other mods: [Custom ModPack based on a modification of FTB Revelation modpack] 

I'm avaible to give more information if it can help.
Thanks for this incredible mod ^^

**Comment by Kotori316** [comment]
Recently, I think QuarryPlus(for 1.12.2 or 1.15.2) consumes too much energy. With the fastest enchantments(Efficiency V, Unbreaking III, Silktouch), it requires about 3000-4000 RF/t, while original version (for 1.7.10) requires 750 RF/t with the same enchantments. Considering machine speed, 1.15.2 quarry seems much faster so its consumption may be well-balanced, but the high consumption will surprise new players.

I'll run 1.7.10 quarry and get the detail of the amount quarry consumes. (Of course pump as well)

**Comment by Alexlion2308** [comment]
Ok, i will test with a higher power supplie, but is it normal that pumpplus consume huge amount ? the quarryplus on blockbreaking with max enchant consume 1kRF on my world instance.

**Comment by Alexlion2308** [comment]
Ok i tested with a creative power source, and it consume 2784RF/t also with pumping but it still stuck about few time of pumping :/ (QuarryPlus Eff5 Fortune3 Unbreak3 and with FastHeadMoving on true)

**Comment by Kotori316** [comment]
Pump consumes 100 RF per 1000 mB (a block). So if water fills 256x256 area, there are 65536 water blocks and pump requires about 700,000 RF(including cost to place frames) to remove 256x256 blocks. Unbreaking doesn't work due to a coding bug. But energy capacity of Quarry is about 130,000 RF. How is it working?

I'm digging 256x256 area of frozen ocean in 1.15.2 and will do in ocean in 1.12.2 and 1.7.10.

I know there are so many mods that can supply huge energy, over 10,000 RF/t. (solar, reactor, etc.)
If FastHeadMoving is true, quarry works 5 times in a tick. Normal quarry requires about 200 RF/t and Fast move quarry may consume over 1000 RF/t.

**Comment by Alexlion2308** [comment]
Okay, its the capacity of the quarry that stop because the amount to pump is too big. Weird for low layer lava lake ? My quarry is around 140k Capacity and it consume all my 1000RF/t with or without FastHeadMoving. And i tried with an unlimited power supplie and it lock, maybe i do not do this with good parameters. Can you provide your test set (what machine etc)?

Thanks again for treating :)

**Comment by Kotori316** [comment]
See [this gist](https://gist.github.com/Kotori316/25d7e51fb3eb388d68e47f0675618eb3). I uploaded some picture that shows the amount of required energy (3rd picture). A picture contains Japanese text, but please don't care. I have only Japanese version of excel.

The 1st picture in gist means pump required about 300,000 RF in a tick. It is not a problem because I added code to solve this. (See [this blame log](https://github.com/Kotori316/QuarryPlus/blame/e662037099c3a28a53127ac44e2a609f14bf54d5/src/main/scala/com/yogpc/qp/machines/base/APowerTile.java#L228)) Quarry continues working.

The 3rd picture shows **quarry requires about 22,000 RF/t** to remove fluids. This causes your stuck.

In 1.12.2 version, I found a mistake in config. The FastHeadMoving is ignored so quarry works 5 times in a tick. I added fix code but I don't generate jar and upload. So quarry enchanted with Efficiency works as Fast move quarry and will consume 1,000 RF/t. **Also, I found bugs of energy calculation of pump. Unbreaking level is always 0.**

My test set
* Minecraft 1.15.2
* developing version of QuarryPlus, based on v15.2.6
* QuarryPlus(quarryplus:quarry) with Efficiency V, Unbreaking III, Fortune III
* Biome is frozen ocean.

The type of fluid does nothing with pump energy. Any fluid requires 100 RF to be removed.

**Comment by Alexlion2308** [comment]
Ok i understand, yeah my creative power source was limited to 20kRF thats because it stuck i think.

You fix that recently right ? You will upload soon a new jar of 12 version or you are waiting more improvment ? (Singleplayer i turn with noenergy for the moment, soon quantum solar panel from tech reborn 😋)

**Comment by Kotori316** [comment]
Uploaded v12.3.7
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2936105

* Unbreaking works for pump.
* You can get energy detail log.
  1. Turn on debug in config. (Change to true)
  2. Start quarry.
  3. Log file is saved in `debug/quarryplus/(data)T(time).csv` and dat(binary) file.
* Fixed quarry was too fast when FastHeadMoving is false.

**Comment by Alexlion2308** [comment]
![IMG_20200421_145025](https://user-images.githubusercontent.com/12431297/79868699-92618900-83e0-11ea-8d86-34064f0bd358.jpg)
![IMG_20200421_145759](https://user-images.githubusercontent.com/12431297/79868711-9a212d80-83e0-11ea-8108-c17295875589.jpg)

I tried on a new world to quary on ocean (to test with huge amount) with 1000RF/t and max 2784RF/t and it works for some layer of 256x256 (with a little part of solid ground) and it stuck about long time, in logs it still consume like working (info debug) but the quarry is stopped. I will test it in real condition with solid ground- Aroma Mining Biome) and I will get you feedback.

**Comment by Kotori316** [comment]
If you don't mind, please give me 3 files as your feedback.
* `debug.log`saved in log folder
* energy detail csv (see my comment above)
* dat
zip them and attach to your comment.

**Comment by Alexlion2308** [comment]
I didn't find csv and dat files do you have exact path, do i restart minecraft after enable debug mode ?

**Comment by Kotori316** [comment]
The debug folder is generated in the same directory as mods folder exists.
![debug_path](https://user-images.githubusercontent.com/28705167/79871220-015dd280-841f-11ea-9898-89eb74a732f2.png)
To generate csv, you need to stop the machine. To stop, just break the block. Also, debug system doesn't work machines which is placed when debug=false. You should restart Minecraft, re-place machine and start again.

**Comment by Alexlion2308** [comment]
Here my debug info, 
The quarry stuck immediately after beginning on the first water block it found (quarry launched on the previous quarry unfinished hole).The quarry worked around 16h09 to 16h11.

Thanks. :)
[issue85DebugInfo.tar.gz](https://github.com/Kotori316/QuarryPlus/files/4510898/issue85DebugInfo.tar.gz)

**Comment by Kotori316** [comment]
Thank you for log file.

It seems quarry "break" water blocks, **NOT "pump"**. Fluids from vanilla are registered with hardness = 100, 67 times as hard as stone, and require 22,000 RF to be removed as a block. BC's oil seems its hardness is 0 so quarry required 0 RF and didn't stop.

I'll find stupid bug and release new version.

**Comment by Kotori316** [comment]
Try [v12.3.8](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2939327).

I **don't** recommend players to use "Old Quarry Plus". I added recipe to convert it to new one(keeping its enchantments).

**Comment by Alexlion2308** [comment]
Yeah. I use v12.3.8 with the QuarryPlus (No longer the old one) and it seems work. I setup a new QuarryPlus on water with energy required and no stucking. I think it's good :D.
Thanks for all your investment :100: 
![2020-04-24_19 03 46](https://user-images.githubusercontent.com/12431297/80239084-e1692180-865f-11ea-966a-063d626d83bc.png)
