### ISSUE TITLE
Can't add both Fortune and silk touch on the quarryplus

### ISSUE THREAD

**Issue by CalimeRon** [Kotori316/QuarryPlus#89]
(First of all : Love this mod).

I can't seem to add both fortune and silk touch through the enchant mover to my quarryplus. Once either is applied, putting a diamond tool with the other enchantment doesn't make it appear in the GUI.

I've looked all over the issues, reddit talks and comments on the main page here, but couldn't find anything resembling. Did I miss something and the feature was removed in the most recent versions ? From what I understood from other discussions you could indeed have both and then use a exclude/include list
I'm playing on the latest 1.12.2 release.

**Comment by Kotori316** [comment]
Thank you for using my mod.

I don't allow player to add incompatible enchantments, like a pair of Fortune and Silktouch, under the default config. But **changing config option `DisableEnchantMoverFromBook` to false** will allow you to move Silktouch and Fortune at the same time.

One more thing, I didn't check List Editor and List Template worked fine. The new quarry(named "QuarryPlus") **doesn't** accept setting from the items. So now new quarry with Fortune and Silktouch works as a miner with only Silktouch for many blocks. Old Quarry(may be disabled in config?) accepts setting but I don't recommend players to use it because of some energy issues(low energy supplier will cause bugs).

It seems possible to implement to new quarry a function of selecting which enchantment to use to break block, but I'm a bit busy this week...

I'll close this issue but feel free to add your comment.

**Comment by CalimeRon** [comment]
So basically I can do what I asked with the currently disabled enchantmoverfrombook, but so far if I want the list editor options it would work only with the old quarry, which is buggy at times. And maybe one day for new quarry.
Thanks a lot for the prompt answer, it's way more clear now. (And feel free to add this list editor on the new quarry anytime :) )

**Comment by Kotori316** [comment]
Now ListEditor and Template work for new QuarryPlus with [v12.4.0](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2961476).

I recommend to use **Template** because I didn't implement GUI of ListEditor so you **can't delete** entry of block. Also template holds setting and only you should do to apply setting is to use the setting-finished template to quarry.

How to use Template
--
Right click any blocks without machine with template to open template GUI, then put block into a slot in GUI and press add. Press "e" to close screen and right click machine to move the setting.

**Comment by Kotori316** [comment]
One more thing.

Once you changed `DisableEnchantMoverFromBook` false, you can move silktouch and fortune with "EnchantMover" from diamond pickaxe, not "BookEnchantmentMover" from enchanted book.

**Comment by CalimeRon** [comment]
Just saw thism it's amazing thank you for implementing it ! 

I created the template and added a few blocks.

Thing is it seems the template holds only whitelist/blacklist right ? Can the template also dictate which blocks to mine with silk touch and which block to mine with fortune?

Or maybe I have to add enchantments to both the newquarryplus and the template then right-click the machine with the template after setting it up ?

Gonna try that.

EDIT: Ok so I ran a few tests, if anyone ever reads this. I hope I got this right, feel free to correct me :) 

**Tools :** 
-Newquarryplus with Silk Touch and Fortune III
-Template with Silk Touch containing Diamond ore and Coal ore
-Template with Fortune containing Redstone Ore
-Diamond Ore, Coal Ore, Redstone Ore and Lapis Lazuli ore in an area

I added both templates to the quarryplus and this appeared in my chest
- Diamond Ore and Coal Ore 
- Redstone (quantity high enough to be consistent with Fortune)
- Lapis lazuli (normal quantity)

Then I removed Diamond Ore from the Silk Touch template, put 3 diamond ores, and received 3 diamonds.

Then I put the same quarry but without applying the templates, and it Silktouched by default

So it seems that
- Silk Touch & Fortune Template work indeed as expected
- When no template is applied, everything will be silktouched even if the quarry holds the Fortune III enchantment alongside Silk Touch
- **Any item out of either template will be mined "normally" without any fortune or silk touch applied, even if newquarryplus has both enchantments** . So before mining it would be wise to set absolutely every ore you expect to encounter in your mining if you want to make sure one of both enchantments applies.

Thanks again !

**Comment by Kotori316** [comment]
A good solution.
1. Get Template with Silktouch.
2. Change the mode. If you want to apply Silktouch, **"Include"**. Fortune, **"Exclude"**.
3. Add blocks you want to apply the enchantment.

Example
* Fortune
  * Diamond Ore
  * Coal Ore
* Silktouch
  * All blocks except Diamond Ore and Coal Ore

Then, open GUI of Silktouch Template, set **Exclude** and add Diamond Ore and Coal Ore. The quarry will apply Fortune for Diamond Ore and Coal Ore and Silktouch for others. As a result you'll get Diamond and Coal as items and other blocks such as Stone, RS Ore, Lapis lazuli Ore.

I added some code(8a15159d0b14ebc7ffccf6c8c2cf8ebde16bc56a) to respect fortune setting. Use template with Fortune and "Include" mode to quarry, and quarry apply Fortune for blocks added in template, Silktouch for blocks that is NOT listed in template.
