### ISSUE TITLE
Quarry Plus Frame stopped generating

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Kotori316/QuarryPlus#97]
**Describe the bug**
After placing and setting the Quarry Plus Markers, I place the Quarry Plus machine and the Quarry Plus Frame starts generating like normal. Then, it just stops as shown in the screenshot. It does this about 50% of the time. I have reset the markers and hope it will finish generating the frame and start mining.

**To Reproduce**
1. Set the Quarry Plus Markers
2. Place the Quarry Plus machine
3. Power machine

- Minecraft: 1.16.1
- Single Player or Multi-Player?: Playing ATM6 on our server.
- Forge: 1.16.1-32.0.75
- This mod (QuarryPlus): v16.0.5
- Other mods: [ATM6 modpack]

![2020-07-22_15 16 46](https://user-images.githubusercontent.com/17887664/88230167-2422a180-cc2f-11ea-8507-46b0c43e85f4.png)

**Comment by ClaudiusMinimus** [comment]
I adjusted the markers and it seems to due to the fact I am mining under an ocean and Quarry Plus does not like water above it

**Comment by Kotori316** [comment]
Use Pump Module. Be careful, the module may remove water located in out of the area.
Then quarry removes water. If quarry stopped during building frames, replace the machine or reload the world.

I'll add some codes to try to prevent this stop but the issue is not easy to reproduce and sensitive to the situation. My test seems working so I'll upload new version.
